### PR TITLE
Fix import Payload and define mutations variable

### PR DESCRIPTION
**Pull request by mateuszz0000**
Added import Payload and define not existing mutations variable

### CODE REVIEW

**Comment by defparam** [comment]
Hi @mateuszz0000,

Thanks for the pull request, could you elaborate more on the issue? The python files in the `configs` directory aren't meant to be standalone python files. These files are executed under the context and scope of smuggler.py - Line 146. When executed in that scope both the Payload library and the mutations variable are defined.

Thanks,
Evan

**Comment by mateuszz0000** [comment]
Agree because it is Python :smiley:. Global variables are not good pattern at all. Problem will occur when you decide to write tests for `render_template` --> it will fail automatically. This `import` is important for better readability, when I read this file for the first time I don't know where is `Payload` definition.

**Comment by defparam** [comment]
OK that's fair, I'm all for readability. Have you tested the changes of `exhaustive.py` by invoking: `python3 smuggler.py -u https://<URL>/ -c exhaustive.py` , it appears to exit early for me without conducting any tests.

**Comment by mateuszz0000** [comment]
Said testing I mean unit testing :smiley:. I can close this PR if you are not sure about these changes :)

**Comment by defparam** [comment]
Thanks for the pull request! at this time I'm going to keep the config files they way they are. However I will look at ways to improve their readability.

Best,
Evan

**Pull request closed without merging**
